print("hello wolrd")
print("+----------+")
print("|   -  -   |")
print("|    __    |")
print("+----------+")
print("+----------+")
print("|   |  |   |")
print("|   |  |   |")
print("|   |  |   |")
print("|   |  |   |")
print("+___|__|___+")
print("|   |  |   |")
print("|   |  |   |")
print("|___|  |___|")
